LoopSend: LoopSend.cu
	nvcc LoopSend.cu -lmpi
LoopSend2: LoopSend2.cu
	nvcc LoopSend2.cu -lmpi
LoopSend3: LoopSend3.cu
	nvcc LoopSend3.cu -lmpi
LoopSend4: LoopSend4.cu
	nvcc LoopSend4.cu -lmpi
MPSend: MPSend.cu
	nvcc MPSend.cu -lmpi -o a.out
MPRecieve: MPRecieve.cu
	nvcc MPRecieve.cu -lmpi -o b.out
Communication: Communication.cu
	nvcc Communication.cu -lmpi